# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20160510_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='photo',
            field=models.FileField(blank=True, max_length=200, upload_to='media_cdn/'),
        ),
    ]
