# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20160512_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['category']},
        ),
        migrations.AlterModelOptions(
            name='tutorialdetail',
            options={'ordering': ['id']},
        ),
    ]
