# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_auto_20160513_0107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['author']},
        ),
    ]
